version: '3.9'

services:
  redis-cache:
    image: redis:7.4.1
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - redis-network

  my-app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
    depends_on:
      - redis-cache
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
